### ISSUE TITLE
Adding an in-memory attachment to an eProcurement response

### ISSUE THREAD

**Issue by frodegill** [TOOP4EU/toop-playground-ng#3]
eu.toop.playground.dp.model.EDMResponseWithAttachment uses eu.toop.playground.dp.model.Attachment, and right now the only way of getting attachments into Attachment seems to be through a File. Could it be possible to also add a byte[] or an InputStream as attachment?

**Comment by kdoul** [comment]
Replaced File with byte array for the Attachment class.
